"""
Hardware Fingerprint License Verification
==========================================
Verifies that a valid license.dat exists and matches this machine's hardware.

license.dat is generated by generate_license.py and must be placed manually
in the same directory as RestaurantPOS.exe by the developer.

If license.dat is missing or the fingerprint doesn't match, the app shows
an error dialog and exits.

Developer contact (shown in the error dialog):
  Name:  Milkiyas
  Phone: 0933245672
"""

import hashlib
import os
import sys
import subprocess
import tkinter as tk
from tkinter import messagebox

DEVELOPER_NAME  = "Milkiyas"
DEVELOPER_PHONE = "0933245672"


def _get_license_path():
    if getattr(sys, 'frozen', False):
        base = os.path.dirname(sys.executable)
    else:
        base = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(base, "license.dat")


LICENSE_FILE = _get_license_path()


# ---------------------------------------------------------------------------
# Hardware info collection
# ---------------------------------------------------------------------------

def _run_wmic(query: str) -> str:
    try:
        result = subprocess.check_output(
            query, shell=True, stderr=subprocess.DEVNULL,
            creationflags=subprocess.CREATE_NO_WINDOW
        )
        lines = result.decode(errors="ignore").strip().splitlines()
        for line in lines:
            line = line.strip()
            if line and not line.lower().startswith(("serialnumber", "uuid",
                                                      "processorid", "name",
                                                      "caption")):
                return line
        return "UNKNOWN"
    except Exception:
        return "UNKNOWN"


def _get_motherboard_serial() -> str:
    return _run_wmic("wmic baseboard get SerialNumber")

def _get_disk_serial() -> str:
    return _run_wmic("wmic diskdrive get SerialNumber")

def _get_os_machine_id() -> str:
    try:
        import winreg
        key = winreg.OpenKey(
            winreg.HKEY_LOCAL_MACHINE,
            r"SOFTWARE\Microsoft\Cryptography"
        )
        value, _ = winreg.QueryValueEx(key, "MachineGuid")
        winreg.CloseKey(key)
        return value
    except Exception:
        return "UNKNOWN"

def _get_cpu_model() -> str:
    return _run_wmic("wmic cpu get Name")


# ---------------------------------------------------------------------------
# Fingerprint generation
# ---------------------------------------------------------------------------

def _normalize(value: str) -> str:
    return value.strip().lower().replace(" ", "").replace("\t", "")


def generate_fingerprint() -> str:
    motherboard = _normalize(_get_motherboard_serial())
    disk        = _normalize(_get_disk_serial())
    machine_id  = _normalize(_get_os_machine_id())
    cpu         = _normalize(_get_cpu_model())
    raw = motherboard + disk + machine_id + cpu
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


# ---------------------------------------------------------------------------
# Error dialog
# ---------------------------------------------------------------------------

def _show_error(title: str, message: str) -> None:
    root = tk.Tk()
    root.withdraw()
    messagebox.showerror(title=title, message=message)
    root.destroy()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def verify() -> None:
    """
    Call this once at application startup.

    - If license.dat is missing → show error and exit (developer must generate it first).
    - If license.dat exists and fingerprint matches → continue normally.
    - If license.dat exists but fingerprint doesn't match → show error and exit.
    """
    # Check if license file exists
    if not os.path.exists(LICENSE_FILE):
        _show_error(
            "License Not Found",
            "⚠️  No license file found for this machine.\n\n"
            "This software requires a valid license to run.\n\n"
            f"Please contact the developer to obtain a license:\n\n"
            f"  Name:  {DEVELOPER_NAME}\n"
            f"  Phone: {DEVELOPER_PHONE}"
        )
        sys.exit(1)

    # Read stored fingerprint
    try:
        with open(LICENSE_FILE, "r") as f:
            stored_fp = f.read().strip()
    except Exception:
        _show_error(
            "License Error",
            "⚠️  Could not read the license file.\n\n"
            f"Please contact the developer:\n\n"
            f"  Name:  {DEVELOPER_NAME}\n"
            f"  Phone: {DEVELOPER_PHONE}"
        )
        sys.exit(1)

    # Compare fingerprints
    current_fp = generate_fingerprint()
    if current_fp != stored_fp:
        _show_error(
            "Unauthorized Copy Detected",
            "⚠️  You are not allowed to use this software on this device.\n\n"
            "This license is registered to a different machine.\n\n"
            f"Please contact the developer to obtain a valid license:\n\n"
            f"  Name:  {DEVELOPER_NAME}\n"
            f"  Phone: {DEVELOPER_PHONE}"
        )
        sys.exit(1)

    # Fingerprint matches — all good
